language: node_js
node_js:
- 10.8.0
branchs:
  only:
  - master
install:
- npm install --production
script:
- npm run build
addons:
  ssh_know_hosts:
  - 172.16.85.219
before_install:
- openssl version
- openssl aes-256-cbc -K $encrypted_53dfaac14d43_key -iv $encrypted_53dfaac14d43_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- whoami
- pwd
- chmod 600 ~/.ssh/id_rsa
