language: node_js
node_js:
- 10.8.0
branches:
  only:
  - master
  - dev
cache: npm
install:
- npm install --production >/dev/null 2>&1
script:
- npm run build
addons:
  ssh_known_hosts:
  - 47.98.153.117
before_install:
- openssl aes-256-cbc -K $encrypted_53dfaac14d43_key -iv $encrypted_53dfaac14d43_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- scp dist/release.tar.gz work@47.98.153.117:/home/work/.travis-release
- ssh work@47.98.153.117 -o StrictHostKeyChecking=no 'cd /home/work/.travis-release &&  tar -xzf release.tar.gz -C /home/work/webserver/estate-server'  