language: node_js
node_js:
- 10.8.0
branchs:
  only:
  - master
cache: npm
install:
- npm install --production >/dev/null 2>&1
script:
- npm run build
addons:
  ssh_know_hosts:
  - 172.16.85.219
before_install:
- openssl aes-256-cbc -K $encrypted_53dfaac14d43_key -iv $encrypted_53dfaac14d43_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- cat ~/.ssh/id_rsa
after_success:
- chmod 600 ~/.ssh/id_rsa
- scp dist/release.tar.gz work@172.16.85.219:/home/work/.travis-release
- ssh work@172.16.85.219 -o StrictHostKeyChecking=no 'cd /home/work/.travis-release &&  tar -xzf release.tar.gz -C /home/work/webserver/estate-server'